### ISSUE TITLE
502 Bad Gateway when visiting nulis.io 

### ISSUE THREAD

**Issue by pvmpa-iscteiulpt** [raymestalez/nulis#19]
Hello,

When I visit this project's official host on https://nulis.io/ , all I'm greeted with is a 502 Bad Gateway error. It's been like this for about a week, if not more. What's going on?

Thanks

**Comment by pvmpa-iscteiulpt** [comment]
It's back up. 

Thanks

**Comment by onatbas** [comment]
Back down again.. @raymestalez
