### ISSUE TITLE
Deskop version, syncing?

### ISSUE THREAD

**Issue by poVoq** [raymestalez/nulis#3]
Is there an option to have the desktop version sync with the online version?

If not, how about writing a Nextcloud plugin to have nulis work in Nextcloud and use it to sync from the desktop version.

**Comment by lumenwrites** [comment]
Desktop is in it's early version, but it's essentially a packaged online app. So you can just create trees in the cloud. I'll be trying to make syncing more obvious and convenient though.

**Comment by poVoq** [comment]
Ok, thanks for the feedback. Issue solved I guess.
